services:
  redis_db:
    image: redis/redis-stack:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  chroma_db:
    image: chromadb/chroma:latest
    container_name: chroma_db
    ports:
      - "8000:8000"  # Expose the port used by Chroma
    volumes:
      - chroma_data:/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  redis_data:
  chroma_data:
  qdrant_data: