services:
  redis_db:
    image: redis/redis-stack:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  chroma_db:
    image: chromadb/chroma:latest
    container_name: chroma_db
    ports:
      - "8000:8000"  # Expose the port used by Chroma
    volumes:
      - chroma_data:/data

  milvus_db:
    image: milvusdb/milvus:v2.5.6
    container_name: milvus_db
    ports:
      - "19530:19530"  # Default Milvus port for gRPC
      - "19121:19121"  # Optional: Milvus HTTP port if needed
    environment:
      TZ: "UTC"      # Set timezone if necessary
    volumes:
      - milvus_data:/var/lib/milvus

volumes:
  redis_data:
  chroma_data:
  milvus_data: